version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis-kv-store
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
